# SPDX-License-Identifier: Apache-2.0
version: '3.5'

networks:
  fabric_test:
    external:
      name: fabric_test

services:

  tdc.fabric.app:
    image: cconsensus/dapp_tdc_fabric:1.0.0
    container_name: dapp.cconsensus.com.br
    hostname: dapp.cconsensus.com.br
    environment:
      # Custom
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - GOPATH=/opt/gopath
      - TZ=America/Sao_Paulo
    ports:
      - 4444:4444
    networks:
      - fabric_test

