# SPDX-License-Identifier: Apache-2.0
version: '3.5'

networks:
  fabric_test:
    external:
      name: fabric_test

services:

  org1dtc.fabric.dapp:
    image: cconsensus/dapp_tdc_fabric:1.0.0
    container_name: org1tdc.cconsensus.com.br
    hostname: org1tdc.cconsensus.com.br
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - GOPATH=/opt/gopath
      - TZ=America/Sao_Paulo
    ports:
      - 4444:4444
    networks:
      - fabric_test
    volumes:
      - ./config/connection-org1_tdc_oracle.json:/app/connection/connection.json
      - ./config/.envorg1:/app/.env
      - ./config/swaggerorg1.json:/app/swagger.json

  org2tdc.fabric.dapp:
    image: cconsensus/dapp_tdc_fabric:1.0.0
    container_name: org2tdc.cconsensus.com.br
    hostname: org2tdc.cconsensus.com.br
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - GOPATH=/opt/gopath
      - TZ=America/Sao_Paulo
    ports:
      - 5555:5555
    networks:
      - fabric_test
    volumes:
      - ./config/connection-org2_tdc_oracle.json:/app/connection/connection.json
      - ./config/.envorg2:/app/.env
      - ./config/swaggerorg2.json:/app/swagger.json

  org3tdc.fabric.dapp:
    image: cconsensus/dapp_tdc_fabric:1.0.0
    container_name: org3tdc.cconsensus.com.br
    hostname: org3tdc.cconsensus.com.br
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - GOPATH=/opt/gopath
      - TZ=America/Sao_Paulo
    ports:
      - 7777:7777
    networks:
      - fabric_test
    volumes:
      - ./config/connection-org3_tdc_oracle.json:/app/connection/connection.json
      - ./config/.envorg3:/app/.env
      - ./config/swaggerorg3.json:/app/swagger.json
